### ISSUE TITLE
playsound dependency blocker

### ISSUE THREAD

**Issue by feddybear** [think-biq/piper-whistle#2]
the `playsound` dependency is currently blocking installation for me, I wonder if that can be replaced

**Comment by BlurryRoots** [comment]
Hey @feddybear, thanks for bringing this up. I'd be curious to how this error manifests. Would you be able to provide some error messages or install logs? What python version are you using? What operating system? Which piper-whistle version are you trying to install?

**Edit**: Removed 'hard' requirement of playsound in version 1.6.233 for now. To activate the preview feature installing playsound manually is required.

**Comment by BlurryRoots** [comment]
Seems like there is no interest in this anymore. Closing for now.
