### ISSUE TITLE
Not obvious how to switch voices or if it should be done elsewhere.

### ISSUE THREAD

**Issue by maxugly** [think-biq/piper-whistle#3]
Hey, awesome lightweight and seemingly somewhat powerful tool! I love the built in package manager for voice models. There is no obvious way how to change between voices. It just seems strange the things that are listed here and '--help'. I can do it in a hacky way, just seems odd to have all this capability and not a basic one. Hopefully I am just missing something simple, would not be the first time.. Thanks!

**Comment by BlurryRoots** [comment]
Hey @maxugly, thanks for the kind words. I am not quite sure what you mean by "switching". Whistle is meant to be similar to a 'package manager'. When you invoke piper itself, you may specify any of the voices installed via whistle. An example would be: `piper -m $(piper_whistle path en_GB-alan-low)`
The -m switch of piper allows you to specify the voice file to be used. So you just have to pick one you have installed and let whistle provide the full path to it.
